### ISSUE TITLE
VariableReplacement

### ISSUE THREAD

**Issue by itskarthikholla** [spullara/mustache.java#234]
Right now behavior for Variable replacement is, if variable found in map it will replace it with corresponding value. else it will replace the variable value with ''

is it possible to override this behavior ?

If variable not found leave it as it is , is it feasible as of now ?

**Comment by spullara** [comment]
Can you give a concrete example so I can ensure I understand the question? Do you mean to leave the brackets as well?

**Comment by itskarthikholla** [comment]
Let take a snippet
```
String input = "data:
      accounts:
      - enable: true
        password: '{{cloud-admin-password}}'
        securitylevel: administrator
        username: '{{cloud-admin-username}}'"

```
Map<String, String> variablesToReplace = new HashMap();
variablesToReplace.put("cloud-admin-password","admin");

in the above example varaibleToReplace is a Map which has only one entry (for Cloud-admin-username as key, admin as value).

final StringWriter writer = new StringWriter();
        DEFAULT_MUSTACHE_FACTORY
                .compile(new StringReader(input), "yaml-loadYamlFromString-" + System.currentTimeMillis())
                .execute(writer, variablesToReplace);
        String ouput = writer.toString();

once above snippet is executed , ouput value will be 
data:
      accounts:
      - enable: true
        **password: ''**
        securitylevel: administrator
        **username: 'admin'**

In our variableToreplaceMap we didn't specify about cloud-admin-password with any value. but by default it is replacing with empty string. 

Is there anyway to avoid this? to have something like if value is not specified keep the variable as it is ?
