### ISSUE TITLE
Quotes rendered with &quot

### ISSUE THREAD

**Issue by gee4vee** [spullara/mustache.java#249]
I have the following template file:

```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: {{name}}
spec:
  schedule: "{{schedule}}"
  data: '{{data}}'
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: {{sinkName}}
```

For the `data` value I'm passing in something like `{\"source\": \"test\"}`. The output file ends up with this for data: `'{&quot;source&quot;: &quot;test&quot;}'`

Is there a way to have actual double quotes instead of `&quot;`?
